---
- name: Check whether apt requires a reboot
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: apt_reboot_if_required_reboot_required_file
  when: ansible_facts["os_family"] == "Debian"

- name: Trigger reboot if required
  ansible.builtin.debug:
    msg: "Notified to reboot due to apt updates"
  when:
    - ansible_facts["os_family"] == "Debian"
    - apt_reboot_if_required_reboot_required_file.stat.exists | default(false)
  changed_when: true
  notify: Reboot
