"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = '[➜](bold blue)'

[directory]
before_repo_root_style = 'black bold dimmed'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '
truncation_symbol = '…/'

[git_status]
conflicted = '↔'
