---
# docker_rootful: install Docker Engine (rootful mode)
# Source: docs/docker/docker engine (rootful).md

- name: Ubuntu branch
  ansible.builtin.include_tasks:
    file: ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Debian branch
  ansible.builtin.include_tasks:
    file: debian.yml
  when: ansible_facts['distribution'] == 'Debian'
