---
# wireguard_client role defaults
#
# Required (no default):
#   wireguard_address:       client IP address(es) for the WireGuard interface
#                            e.g. "10.140.113.2/24, fdcc:fade:beee:deed:feed:beef:0:2/112"
#   wireguard_server_pubkey: server's WireGuard public key
#   wireguard_endpoint:      server's WireGuard endpoint (IP:port)

wireguard_allowedips: "10.140.113.0/24, fdcc:fade:beee:deed:feed:beef::/112"
wireguard_dns: ""
wireguard_mtu: 1420
wireguard_keepalive: 25
