---
proxmox_new_username: tim
proxmox_new_user_shell: /bin/zsh
# Groups that are common in Proxmox VMs. Some may not exist in LXC — errors are ignored.
proxmox_new_user_groups:
  - adm
  - sudo
  - dip
  - plugdev
  - dialout
  - audio
  - video
