---
# Test playbook: test a wider set of roles in Docker
- name: Test common roles in Docker
  hosts: localhost
  connection: local
  gather_facts: true
  become: true

  roles:
    - role: common_base
    - role: apt_nycu_mirror
    - role: apt_cacher_ng
    - role: vim
    - role: git
    - role: tmux
    - role: pigz
