---
# Setup zsh config directories

- name: Ensure zsh config directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ setup_user }}"
    group: "{{ setup_user }}"
    mode: "0755"
  loop:
    - "{{ setup_user_home }}/.config"
    - "{{ setup_user_home }}/.config/zsh"
    - "{{ setup_user_home }}/.config/zsh/non-interactive"
    - "{{ setup_user_home }}/.config/zsh/interactive"
