---
# common_base: ensure the system is up-to-date
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: full

- name: Remove unused packages
  ansible.builtin.apt:
    autoremove: true
    purge: true

- name: Deploy aptu update script for apt
  ansible.builtin.copy:
    src: apt.update.zsh
    dest: "{{ setup_user_home }}/.config/zsh/update/apt.update.zsh"
    owner: "{{ setup_user }}"
    group: "{{ setup_user }}"
    mode: "0644"

- name: Deploy aptu update script for snap
  ansible.builtin.copy:
    src: snap.update.zsh
    dest: "{{ setup_user_home }}/.config/zsh/update/snap.update.zsh"
    owner: "{{ setup_user }}"
    group: "{{ setup_user }}"
    mode: "0644"
