---
# common_base: ensure the system is up-to-date
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: full

- name: Remove unused packages
  ansible.builtin.apt:
    autoremove: true
    purge: true
