LoginGraceTime 10s
PermitRootLogin prohibit-password
AuthorizedKeysFile .ssh/authorized_keys
PasswordAuthentication no
PrintMotd yes
ClientAliveInterval 120
ClientAliveCountMax 3
MaxStartups 10:30:20
